name: STM32 EMBEDDED PROJECT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  host:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure 
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build --output-on-failure

  build-arm:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install ARM GNU Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '15.3.Rel1'

    - name: Configure (ARM toolchain) 
      run: cmake -S . -B build-arm -DCMAKE_TOOLCHAIN_FILE=cmake/arm-none-eabi.cmake

    - name: Build firmware
      run: cmake --build build-arm


